"""Classify a file's role from path + content heuristics, config-overridable per glob.

Roles drive how strictly a file is audited (see ``config.ResolvedConfig`` role policy).
Tests are classified, never silently dropped.
"""

import ast
from fnmatch import fnmatch

from auditor.models import FileRole

_TEST_PATH_GLOBS = ("**/tests/**", "**/test/**", "test_*.py", "*_test.py", "tests/*.py")
_TEST_SUPPORT_NAMES = ("conftest.py", "factories.py", "factory.py", "fixtures.py")
_TEST_SUPPORT_GLOBS = ("**/fixtures/**", "**/factories/**")
_GENERATED_SUFFIXES = ("_pb2.py", "_pb2_grpc.py", ".gen.py")
_GENERATED_MARKERS = (
    "# generated by",
    "# autogenerated",
    "# do not edit",
    "@generated",
)


class _SourceFacts:
    """Content-derived facts about one module — parses the source once and answers the
    questions classification needs (instead of re-parsing per question)."""

    def __init__(self, source: str) -> None:
        self._head = source[:2000].lower()
        try:
            self.tree: ast.Module | None = ast.parse(source)
        except SyntaxError:
            self.tree = None

    @property
    def is_generated(self) -> bool:
        return any(marker in self._head for marker in _GENERATED_MARKERS)

    @property
    def defines_tests(self) -> bool:
        if self.tree is None:
            return False
        for node in ast.walk(self.tree):
            if isinstance(
                node, ast.FunctionDef | ast.AsyncFunctionDef
            ) and node.name.startswith("test_"):
                return True
            if isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
                return True
        return False

    @property
    def looks_like_tests(self) -> bool:
        if self.tree is None:
            return False
        return (
            any(_imports_test_framework(n) for n in ast.walk(self.tree))
            and self.defines_tests
        )

    @property
    def is_script(self) -> bool:
        if self.tree is None:
            return False
        for node in self.tree.body:
            if isinstance(node, ast.If) and _tests_dunder_name(node.test):
                return True
        return False


class RoleClassifier:
    """Decides a file's :class:`FileRole`. Construct once per scan with the repo's
    ``role_globs`` (config overrides), then call :meth:`classify` per file."""

    def __init__(self, role_globs: dict[FileRole, list[str]] | None = None) -> None:
        self.role_globs = role_globs or {}

    def classify(self, rel_path: str, source: str | None = None) -> FileRole:
        for role, globs in self.role_globs.items():
            if _matches_any(rel_path, tuple(globs)):
                return role

        name = rel_path.rsplit("/", 1)[-1]
        facts = _SourceFacts(source) if source is not None else None

        if name.endswith(_GENERATED_SUFFIXES) or (facts and facts.is_generated):
            return FileRole.GENERATED

        if name in _TEST_SUPPORT_NAMES or _matches_any(rel_path, _TEST_SUPPORT_GLOBS):
            return FileRole.TEST_SUPPORT

        in_test_dir = _matches_any(rel_path, _TEST_PATH_GLOBS)
        if in_test_dir or (facts and facts.looks_like_tests):
            # A module under tests/ with no test_* functions is support code.
            if facts and in_test_dir and not facts.defines_tests:
                return FileRole.TEST_SUPPORT
            return FileRole.TEST

        if facts and facts.is_script:
            return FileRole.SCRIPT

        return FileRole.PRODUCTION


def _matches_any(rel_path: str, globs: tuple[str, ...]) -> bool:
    name = rel_path.rsplit("/", 1)[-1]
    return any(fnmatch(rel_path, g) or fnmatch(name, g) for g in globs)


def _imports_test_framework(node: ast.AST) -> bool:
    if isinstance(node, ast.Import):
        return any(a.name.split(".")[0] in ("pytest", "unittest") for a in node.names)
    if isinstance(node, ast.ImportFrom):
        return (node.module or "").split(".")[0] in ("pytest", "unittest")
    return False


def _tests_dunder_name(test: ast.expr) -> bool:
    return (
        isinstance(test, ast.Compare)
        and isinstance(test.left, ast.Name)
        and test.left.id == "__name__"
    )
