import type { GraphPayload } from "./types";

export const sample: GraphPayload = {
  meta: { theme: "dark", accent: "#7C7CFF", node_cap: 200 },
  clusters: [
    { cluster_id: 0, label: "core", member_count: 3, agg_rank: 0.9 },
    { cluster_id: 1, label: "utils", member_count: 2, agg_rank: 0.4 },
  ],
  nodes: [
    {
      id: "auditor.graph.viz::build_payload",
      label: "build_payload",
      type: "function",
      lang: "python",
      module: "auditor.graph.viz",
      path: "auditor/graph/viz.py",
      line: 34,
      rank: 0.42,
      cluster: 0,
      role: "hub",
      findings: [],
    },
    {
      id: "auditor.graph.model::NodeKind",
      label: "NodeKind",
      type: "class",
      lang: "python",
      module: "auditor.graph.model",
      path: "auditor/graph/model.py",
      line: 10,
      rank: 0.31,
      cluster: 0,
      role: "utility",
      findings: ["GRAPH-001"],
    },
    {
      id: "auditor.graph.rank::compute",
      label: "compute",
      type: "function",
      lang: "python",
      module: "auditor.graph.rank",
      path: "auditor/graph/rank.py",
      line: 5,
      rank: 0.17,
      cluster: 0,
      role: "worker",
      findings: [],
    },
    {
      id: "auditor.graph.cluster::run",
      label: "run",
      type: "function",
      lang: "python",
      module: "auditor.graph.cluster",
      path: "auditor/graph/cluster.py",
      line: 12,
      rank: 0.22,
      cluster: 1,
      role: "worker",
      findings: [],
    },
    {
      id: "auditor.graph.tokens::count",
      label: "count",
      type: "function",
      lang: "python",
      module: "auditor.graph.tokens",
      path: "auditor/graph/tokens.py",
      line: 8,
      rank: 0.18,
      cluster: 1,
      role: "utility",
      findings: [],
    },
  ],
  edges: [
    { source: "auditor.graph.viz::build_payload", target: "auditor.graph.model::NodeKind", kind: "calls", weight: 1.0 },
    { source: "auditor.graph.viz::build_payload", target: "auditor.graph.rank::compute", kind: "calls", weight: 0.8 },
    { source: "auditor.graph.viz::build_payload", target: "auditor.graph.cluster::run", kind: "calls", weight: 0.6 },
    { source: "auditor.graph.rank::compute", target: "auditor.graph.tokens::count", kind: "calls", weight: 0.5 },
  ],
};
