/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router. Do not edit.
export const routeTree = {
  id: "__root__",
  children: { dashboard: { id: "/dashboard" }, alerts: { id: "/alerts" } },
} as any;

export function buildRouteTree(a: any, b: any, c: any, d: any, e: any, f: any, g: any) {
  return [a, b, c, d, e, f, g];
}
